[[redirects]]
  from = "/about"
  to = "/about.html"
  status = 200

[[redirects]]
  from = "/consultation"
  to = "/consultation.html"
  status = 200

[[redirects]]
  from = "/contact"
  to = "/contact.html"
  status = 200

[[redirects]]
  from = "/practices"
  to = "/practices.html"
  status = 200

[[redirects]]
  from = "/team"
  to = "/team.html"
  status = 200

[[redirects]]
  from = "/why"
  to = "/why.html"
  status = 200
